create sequence admin_user_id_seq start with 100000 increment by 1;

create table admin_users (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    admin_user_id bigint not null,
    username varchar(64) not null,
    password_hash varchar(255) not null,
    display_name varchar(64) not null,
    mobile_masked varchar(32),
    email_masked varchar(128),
    admin_status varchar(32) not null,
    permission_version bigint not null default 1,
    last_login_time timestamptz
);

comment on table admin_users is '后台管理员表，保存后台管理员账号、登录状态和权限版本';
comment on column admin_users.id is '数据库内部自增主键，只允许管理后台服务内部使用';
comment on column admin_users.created_time is '创建时间';
comment on column admin_users.updated_time is '更新时间';
comment on column admin_users.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column admin_users.admin_user_id is '后台管理员业务主键';
comment on column admin_users.username is '后台登录账号名';
comment on column admin_users.password_hash is '后台登录密码哈希';
comment on column admin_users.display_name is '后台展示名称';
comment on column admin_users.mobile_masked is '脱敏手机号，用于后台安全联系和审计展示';
comment on column admin_users.email_masked is '脱敏邮箱，用于后台安全联系和审计展示';
comment on column admin_users.admin_status is '管理员状态，如 ACTIVE、DISABLED、LOCKED';
comment on column admin_users.permission_version is '权限版本，角色或权限变更后递增，用于使旧 Token 失效';
comment on column admin_users.last_login_time is '最近一次后台登录时间';

create unique index uk_admin_users_admin_user_id_active on admin_users (admin_user_id) where is_delete = 0;
create unique index uk_admin_users_username_active on admin_users (username) where is_delete = 0;
create index idx_admin_users_status on admin_users (admin_status) where is_delete = 0;
