create table auth_accounts (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    account_id bigint not null,
    user_id bigint not null,
    account_name varchar(64),
    phone varchar(32),
    email varchar(128),
    account_status varchar(32) not null,
    registered_channel varchar(32),
    last_login_time timestamptz
);

comment on table auth_accounts is '认证账号表，保存登录账号基础身份、账号状态和用户业务主键关联';
comment on column auth_accounts.id is '数据库内部自增主键，只允许认证服务内部使用';
comment on column auth_accounts.created_time is '创建时间';
comment on column auth_accounts.updated_time is '更新时间';
comment on column auth_accounts.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column auth_accounts.account_id is '账号业务主键，用于认证服务对外引用账号';
comment on column auth_accounts.user_id is '用户业务主键，关联用户服务的用户身份';
comment on column auth_accounts.account_name is '账号名，可用于账号名登录';
comment on column auth_accounts.phone is '手机号，可用于手机号登录';
comment on column auth_accounts.email is '邮箱，可用于邮箱登录';
comment on column auth_accounts.account_status is '账号状态，如 NORMAL、DISABLED、LOCKED';
comment on column auth_accounts.registered_channel is '注册来源，如 IOS、WEB、ADMIN';
comment on column auth_accounts.last_login_time is '最近一次登录成功时间';

create unique index uk_auth_accounts_account_id_active on auth_accounts (account_id) where is_delete = 0;
create unique index uk_auth_accounts_user_id_active on auth_accounts (user_id) where is_delete = 0;
create unique index uk_auth_accounts_account_name_active on auth_accounts (account_name) where is_delete = 0 and account_name is not null;
create unique index uk_auth_accounts_phone_active on auth_accounts (phone) where is_delete = 0 and phone is not null;
create unique index uk_auth_accounts_email_active on auth_accounts (email) where is_delete = 0 and email is not null;

create table auth_credentials (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    credential_id bigint not null,
    account_id bigint not null,
    credential_type varchar(32) not null,
    password_hash varchar(255),
    hash_algorithm varchar(64)
);

comment on table auth_credentials is '认证凭证表，保存账号登录凭证，MVP 阶段主要保存密码哈希';
comment on column auth_credentials.id is '数据库内部自增主键，只允许认证服务内部使用';
comment on column auth_credentials.created_time is '创建时间';
comment on column auth_credentials.updated_time is '更新时间';
comment on column auth_credentials.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column auth_credentials.credential_id is '凭证业务主键';
comment on column auth_credentials.account_id is '账号业务主键，关联 auth_accounts.account_id';
comment on column auth_credentials.credential_type is '凭证类型，如 PASSWORD';
comment on column auth_credentials.password_hash is '密码哈希值，禁止保存明文密码';
comment on column auth_credentials.hash_algorithm is '密码哈希算法标识，如 PBKDF2WithHmacSHA256';

create unique index uk_auth_credentials_credential_id_active on auth_credentials (credential_id) where is_delete = 0;
create unique index uk_auth_credentials_account_password_active on auth_credentials (account_id, credential_type) where is_delete = 0;

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    token_id bigint not null,
    account_id bigint not null,
    token_hash varchar(255) not null,
    expires_time timestamptz not null,
    revoked_time timestamptz,
    token_status varchar(32) not null
);

comment on table refresh_tokens is '刷新令牌表，保存 Refresh Token 哈希、过期时间和撤销状态';
comment on column refresh_tokens.id is '数据库内部自增主键，只允许认证服务内部使用';
comment on column refresh_tokens.created_time is '创建时间';
comment on column refresh_tokens.updated_time is '更新时间';
comment on column refresh_tokens.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column refresh_tokens.token_id is '刷新令牌业务主键';
comment on column refresh_tokens.account_id is '账号业务主键，关联 auth_accounts.account_id';
comment on column refresh_tokens.token_hash is 'Refresh Token 哈希值，禁止保存明文 Token';
comment on column refresh_tokens.expires_time is 'Refresh Token 过期时间';
comment on column refresh_tokens.revoked_time is 'Refresh Token 被撤销时间';
comment on column refresh_tokens.token_status is 'Token 状态，如 ACTIVE、REVOKED、EXPIRED';

create unique index uk_refresh_tokens_token_id_active on refresh_tokens (token_id) where is_delete = 0;
create index idx_refresh_tokens_account_status on refresh_tokens (account_id, token_status) where is_delete = 0;

create table login_logs (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    login_log_id bigint not null,
    account_id bigint,
    login_type varchar(32) not null,
    login_result varchar(32) not null,
    ip_address varchar(64),
    user_agent varchar(512)
);

comment on table login_logs is '登录日志表，记录登录行为，用于安全审计和异常登录分析';
comment on column login_logs.id is '数据库内部自增主键，只允许认证服务内部使用';
comment on column login_logs.created_time is '创建时间';
comment on column login_logs.updated_time is '更新时间';
comment on column login_logs.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column login_logs.login_log_id is '登录日志业务主键';
comment on column login_logs.account_id is '账号业务主键，登录失败且账号不存在时可为空';
comment on column login_logs.login_type is '登录方式，如 PHONE、EMAIL、ACCOUNT_NAME';
comment on column login_logs.login_result is '登录结果，如 SUCCESS、FAILED';
comment on column login_logs.ip_address is '登录请求 IP 地址';
comment on column login_logs.user_agent is '登录设备或浏览器 User-Agent';

create unique index uk_login_logs_login_log_id_active on login_logs (login_log_id) where is_delete = 0;
create index idx_login_logs_account_time on login_logs (account_id, created_time desc) where is_delete = 0;
