server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: foodmap-media-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:${FOODMAP_PROFILE:local}}
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}

foodmap:
  env:
    profile: ${SPRING_PROFILES_ACTIVE:${FOODMAP_PROFILE:local}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
