server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: foodmap-community-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

management:
  endpoints:
    web:
      exposure:
        include: health,info
