create table users (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    user_id bigint not null,
    account_id bigint not null,
    nickname varchar(64) not null,
    avatar_media_id bigint,
    user_status varchar(32) not null,
    searchable smallint not null default 1
);

comment on table users is '用户主表，保存用户核心身份、昵称、头像和用户状态';
comment on column users.id is '数据库内部自增主键，只允许用户服务内部使用';
comment on column users.created_time is '创建时间';
comment on column users.updated_time is '更新时间';
comment on column users.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column users.user_id is '用户业务主键，用于跨服务引用用户';
comment on column users.account_id is '认证账号业务主键，来源于认证服务';
comment on column users.nickname is '用户昵称';
comment on column users.avatar_media_id is '头像媒体业务主键，关联媒体服务 media_id';
comment on column users.user_status is '用户状态，如 NORMAL、DISABLED';
comment on column users.searchable is '是否允许被搜索，1-允许，0-不允许';

create unique index uk_users_user_id_active on users (user_id) where is_delete = 0;
create unique index uk_users_account_id_active on users (account_id) where is_delete = 0;

create table user_profiles (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    profile_id bigint not null,
    user_id bigint not null,
    city_code varchar(32),
    city_name varchar(64),
    bio varchar(255),
    gender varchar(32),
    birthday date
);

comment on table user_profiles is '用户资料表，保存城市、简介、性别和生日等展示资料';
comment on column user_profiles.id is '数据库内部自增主键，只允许用户服务内部使用';
comment on column user_profiles.created_time is '创建时间';
comment on column user_profiles.updated_time is '更新时间';
comment on column user_profiles.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column user_profiles.profile_id is '用户资料业务主键';
comment on column user_profiles.user_id is '用户业务主键，关联 users.user_id';
comment on column user_profiles.city_code is '用户所在城市编码';
comment on column user_profiles.city_name is '用户所在城市名称';
comment on column user_profiles.bio is '用户个人简介';
comment on column user_profiles.gender is '性别，可选字段';
comment on column user_profiles.birthday is '生日，可选字段';

create unique index uk_user_profiles_profile_id_active on user_profiles (profile_id) where is_delete = 0;
create unique index uk_user_profiles_user_id_active on user_profiles (user_id) where is_delete = 0;

create table user_settings (
    id bigint generated by default as identity primary key,
    created_time timestamptz not null,
    updated_time timestamptz not null,
    is_delete smallint not null default 0,
    setting_id bigint not null,
    user_id bigint not null,
    default_visibility_type varchar(32) not null,
    allow_friend_request smallint not null default 1,
    allow_search_by_phone smallint not null default 0,
    allow_search_by_email smallint not null default 0
);

comment on table user_settings is '用户设置表，保存隐私偏好和默认推荐可见范围';
comment on column user_settings.id is '数据库内部自增主键，只允许用户服务内部使用';
comment on column user_settings.created_time is '创建时间';
comment on column user_settings.updated_time is '更新时间';
comment on column user_settings.is_delete is '是否逻辑删除，0-未删除，1-已删除';
comment on column user_settings.setting_id is '用户设置业务主键';
comment on column user_settings.user_id is '用户业务主键，关联 users.user_id';
comment on column user_settings.default_visibility_type is '默认推荐可见范围，如 PRIVATE、FRIENDS、PUBLIC';
comment on column user_settings.allow_friend_request is '是否允许收到好友申请，1-允许，0-不允许';
comment on column user_settings.allow_search_by_phone is '是否允许通过手机号搜索到本人，1-允许，0-不允许';
comment on column user_settings.allow_search_by_email is '是否允许通过邮箱搜索到本人，1-允许，0-不允许';

create unique index uk_user_settings_setting_id_active on user_settings (setting_id) where is_delete = 0;
create unique index uk_user_settings_user_id_active on user_settings (user_id) where is_delete = 0;
