spring:
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  flyway:
    enabled: ${USER_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
