create sequence if not exists api_access_log_id_seq
    start with 1000000001
    increment by 1
    minvalue 1
    no maxvalue
    cache 50;

create table if not exists api_access_log (
    id bigint generated by default as identity primary key,
    access_log_id bigint not null default nextval('api_access_log_id_seq'),
    request_id varchar(128) not null,
    trace_id varchar(128) not null,
    span_id varchar(128),
    service_name varchar(128) not null,
    event_name varchar(128) not null,
    log_level varchar(16) not null,
    http_method varchar(16) not null,
    request_path varchar(500) not null,
    http_status integer not null,
    duration_ms bigint not null,
    client_ip_masked varchar(64),
    account_id bigint,
    user_id bigint,
    gateway_route_id varchar(128),
    error_code varchar(128),
    occurred_time timestamptz not null,
    source_topic varchar(128),
    source_partition integer,
    source_offset bigint,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now(),
    is_delete smallint not null default 0,
    constraint uk_api_access_log_access_log_id unique (access_log_id),
    constraint uk_api_access_log_source unique (source_topic, source_partition, source_offset)
);

create index if not exists idx_api_access_log_request_id
    on api_access_log (request_id)
    where is_delete = 0;

create index if not exists idx_api_access_log_trace_id
    on api_access_log (trace_id)
    where is_delete = 0;

create index if not exists idx_api_access_log_occurred_time
    on api_access_log (occurred_time desc)
    where is_delete = 0;

create index if not exists idx_api_access_log_service_time
    on api_access_log (service_name, occurred_time desc)
    where is_delete = 0;

create index if not exists idx_api_access_log_status_time
    on api_access_log (http_status, occurred_time desc)
    where is_delete = 0;

comment on sequence api_access_log_id_seq is '接口访问摘要日志业务主键序列';

comment on table api_access_log is '接口访问摘要日志表，独立日志 PostgreSQL 保存 15 天';
comment on column api_access_log.id is '数据库自增主键，仅用于日志库内部定位';
comment on column api_access_log.access_log_id is '接口访问摘要日志业务主键';
comment on column api_access_log.request_id is '请求流水号，用于查询一次接口调用相关日志';
comment on column api_access_log.trace_id is '链路追踪号，用于串联跨服务调用日志';
comment on column api_access_log.span_id is '当前日志所在调用片段编号';
comment on column api_access_log.service_name is '产生日志的服务名称';
comment on column api_access_log.event_name is '访问日志事件名，如 api.access.completed 或 api.access.slow';
comment on column api_access_log.log_level is '日志等级，如 INFO、WARN、ERROR';
comment on column api_access_log.http_method is 'HTTP 请求方法';
comment on column api_access_log.request_path is 'HTTP 请求路径，不包含敏感请求体';
comment on column api_access_log.http_status is 'HTTP 响应状态码';
comment on column api_access_log.duration_ms is '接口耗时，单位毫秒';
comment on column api_access_log.client_ip_masked is '脱敏后的客户端 IP 摘要';
comment on column api_access_log.account_id is '认证账号业务主键，可为空';
comment on column api_access_log.user_id is '用户业务主键，可为空';
comment on column api_access_log.gateway_route_id is '网关路由标识，可为空';
comment on column api_access_log.error_code is '稳定业务错误码或系统错误码，可为空';
comment on column api_access_log.occurred_time is '接口访问发生时间';
comment on column api_access_log.source_topic is '来源 Kafka topic';
comment on column api_access_log.source_partition is '来源 Kafka 分区';
comment on column api_access_log.source_offset is '来源 Kafka offset';
comment on column api_access_log.created_time is '记录创建时间';
comment on column api_access_log.updated_time is '记录更新时间';
comment on column api_access_log.is_delete is '逻辑删除标记，0 表示未删除，1 表示已删除';
