create sequence if not exists log_archive_record_id_seq
    start with 1000000001
    increment by 1
    minvalue 1
    no maxvalue
    cache 50;

create table if not exists log_archive_records (
    id bigint generated by default as identity primary key,
    archive_id bigint not null default nextval('log_archive_record_id_seq'),
    archive_type varchar(64) not null,
    window_start_time timestamptz not null,
    window_end_time timestamptz not null,
    source_index_pattern varchar(128) not null,
    storage_provider varchar(32) not null,
    bucket_name varchar(128) not null,
    object_key varchar(500) not null,
    archive_status varchar(32) not null,
    retry_count integer not null default 0,
    failure_reason varchar(500),
    started_time timestamptz,
    completed_time timestamptz,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now(),
    is_delete smallint not null default 0,
    constraint uk_log_archive_record_archive_id unique (archive_id),
    constraint uk_log_archive_record_window unique (archive_type, window_start_time, window_end_time)
);

create index if not exists idx_log_archive_records_status_time
    on log_archive_records (archive_status, window_start_time)
    where is_delete = 0;

create index if not exists idx_log_archive_records_window
    on log_archive_records (window_start_time, window_end_time)
    where is_delete = 0;

comment on sequence log_archive_record_id_seq is '日志归档记录业务主键序列';

comment on table log_archive_records is '日志归档记录表，记录全量日志归档窗口、对象存储位置和处理状态';
comment on column log_archive_records.id is '数据库自增主键，仅用于日志库内部定位';
comment on column log_archive_records.archive_id is '日志归档记录业务主键';
comment on column log_archive_records.archive_type is '归档类型，如 FULL_LOG_DAILY';
comment on column log_archive_records.window_start_time is '归档日志窗口开始时间，闭区间';
comment on column log_archive_records.window_end_time is '归档日志窗口结束时间，开区间';
comment on column log_archive_records.source_index_pattern is '来源 Elasticsearch 索引模式';
comment on column log_archive_records.storage_provider is '归档存储提供方，如 OSS';
comment on column log_archive_records.bucket_name is '归档对象存储桶名称';
comment on column log_archive_records.object_key is '归档对象存储 Key';
comment on column log_archive_records.archive_status is '归档状态，如 PENDING、RUNNING、SUCCESS、FAILED';
comment on column log_archive_records.retry_count is '归档重试次数';
comment on column log_archive_records.failure_reason is '归档失败原因摘要';
comment on column log_archive_records.started_time is '归档开始时间';
comment on column log_archive_records.completed_time is '归档完成时间';
comment on column log_archive_records.created_time is '记录创建时间';
comment on column log_archive_records.updated_time is '记录更新时间';
comment on column log_archive_records.is_delete is '逻辑删除标记，0 表示未删除，1 表示已删除';
